/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SavesIndexRouteImport } from "./routes/saves/index"
import { Route as DebugIndexRouteImport } from "./routes/debug/index"
import { Route as CharactersIndexRouteImport } from "./routes/characters/index"
import { Route as GameSettingsRouteImport } from "./routes/game/settings"
import { Route as GamePlayRouteImport } from "./routes/game/play"
import { Route as GameHeroesRouteImport } from "./routes/game/heroes"
import { Route as DebugTerrainRouteImport } from "./routes/debug/terrain"
import { Route as DebugLlmRouteImport } from "./routes/debug/llm"
import { Route as DebugEncountersRouteImport } from "./routes/debug/encounters"
import { Route as CharactersCreateRouteImport } from "./routes/characters/create"
import { Route as SavesManageSessionIdRouteImport } from "./routes/saves/manage.$sessionId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const SavesIndexRoute = SavesIndexRouteImport.update({
  id: "/saves/",
  path: "/saves/",
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexRoute = DebugIndexRouteImport.update({
  id: "/debug/",
  path: "/debug/",
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: "/characters/",
  path: "/characters/",
  getParentRoute: () => rootRouteImport,
} as any)
const GameSettingsRoute = GameSettingsRouteImport.update({
  id: "/game/settings",
  path: "/game/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: "/game/play",
  path: "/game/play",
  getParentRoute: () => rootRouteImport,
} as any)
const GameHeroesRoute = GameHeroesRouteImport.update({
  id: "/game/heroes",
  path: "/game/heroes",
  getParentRoute: () => rootRouteImport,
} as any)
const DebugTerrainRoute = DebugTerrainRouteImport.update({
  id: "/debug/terrain",
  path: "/debug/terrain",
  getParentRoute: () => rootRouteImport,
} as any)
const DebugLlmRoute = DebugLlmRouteImport.update({
  id: "/debug/llm",
  path: "/debug/llm",
  getParentRoute: () => rootRouteImport,
} as any)
const DebugEncountersRoute = DebugEncountersRouteImport.update({
  id: "/debug/encounters",
  path: "/debug/encounters",
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersCreateRoute = CharactersCreateRouteImport.update({
  id: "/characters/create",
  path: "/characters/create",
  getParentRoute: () => rootRouteImport,
} as any)
const SavesManageSessionIdRoute = SavesManageSessionIdRouteImport.update({
  id: "/saves/manage/$sessionId",
  path: "/saves/manage/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/characters/create": typeof CharactersCreateRoute
  "/debug/encounters": typeof DebugEncountersRoute
  "/debug/llm": typeof DebugLlmRoute
  "/debug/terrain": typeof DebugTerrainRoute
  "/game/heroes": typeof GameHeroesRoute
  "/game/play": typeof GamePlayRoute
  "/game/settings": typeof GameSettingsRoute
  "/characters/": typeof CharactersIndexRoute
  "/debug/": typeof DebugIndexRoute
  "/saves/": typeof SavesIndexRoute
  "/saves/manage/$sessionId": typeof SavesManageSessionIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/characters/create": typeof CharactersCreateRoute
  "/debug/encounters": typeof DebugEncountersRoute
  "/debug/llm": typeof DebugLlmRoute
  "/debug/terrain": typeof DebugTerrainRoute
  "/game/heroes": typeof GameHeroesRoute
  "/game/play": typeof GamePlayRoute
  "/game/settings": typeof GameSettingsRoute
  "/characters": typeof CharactersIndexRoute
  "/debug": typeof DebugIndexRoute
  "/saves": typeof SavesIndexRoute
  "/saves/manage/$sessionId": typeof SavesManageSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/characters/create": typeof CharactersCreateRoute
  "/debug/encounters": typeof DebugEncountersRoute
  "/debug/llm": typeof DebugLlmRoute
  "/debug/terrain": typeof DebugTerrainRoute
  "/game/heroes": typeof GameHeroesRoute
  "/game/play": typeof GamePlayRoute
  "/game/settings": typeof GameSettingsRoute
  "/characters/": typeof CharactersIndexRoute
  "/debug/": typeof DebugIndexRoute
  "/saves/": typeof SavesIndexRoute
  "/saves/manage/$sessionId": typeof SavesManageSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/characters/create"
    | "/debug/encounters"
    | "/debug/llm"
    | "/debug/terrain"
    | "/game/heroes"
    | "/game/play"
    | "/game/settings"
    | "/characters/"
    | "/debug/"
    | "/saves/"
    | "/saves/manage/$sessionId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/characters/create"
    | "/debug/encounters"
    | "/debug/llm"
    | "/debug/terrain"
    | "/game/heroes"
    | "/game/play"
    | "/game/settings"
    | "/characters"
    | "/debug"
    | "/saves"
    | "/saves/manage/$sessionId"
  id:
    | "__root__"
    | "/"
    | "/characters/create"
    | "/debug/encounters"
    | "/debug/llm"
    | "/debug/terrain"
    | "/game/heroes"
    | "/game/play"
    | "/game/settings"
    | "/characters/"
    | "/debug/"
    | "/saves/"
    | "/saves/manage/$sessionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersCreateRoute: typeof CharactersCreateRoute
  DebugEncountersRoute: typeof DebugEncountersRoute
  DebugLlmRoute: typeof DebugLlmRoute
  DebugTerrainRoute: typeof DebugTerrainRoute
  GameHeroesRoute: typeof GameHeroesRoute
  GamePlayRoute: typeof GamePlayRoute
  GameSettingsRoute: typeof GameSettingsRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  DebugIndexRoute: typeof DebugIndexRoute
  SavesIndexRoute: typeof SavesIndexRoute
  SavesManageSessionIdRoute: typeof SavesManageSessionIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/saves/": {
      id: "/saves/"
      path: "/saves"
      fullPath: "/saves/"
      preLoaderRoute: typeof SavesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/debug/": {
      id: "/debug/"
      path: "/debug"
      fullPath: "/debug/"
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/characters/": {
      id: "/characters/"
      path: "/characters"
      fullPath: "/characters/"
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/settings": {
      id: "/game/settings"
      path: "/game/settings"
      fullPath: "/game/settings"
      preLoaderRoute: typeof GameSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/play": {
      id: "/game/play"
      path: "/game/play"
      fullPath: "/game/play"
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/game/heroes": {
      id: "/game/heroes"
      path: "/game/heroes"
      fullPath: "/game/heroes"
      preLoaderRoute: typeof GameHeroesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/debug/terrain": {
      id: "/debug/terrain"
      path: "/debug/terrain"
      fullPath: "/debug/terrain"
      preLoaderRoute: typeof DebugTerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/debug/llm": {
      id: "/debug/llm"
      path: "/debug/llm"
      fullPath: "/debug/llm"
      preLoaderRoute: typeof DebugLlmRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/debug/encounters": {
      id: "/debug/encounters"
      path: "/debug/encounters"
      fullPath: "/debug/encounters"
      preLoaderRoute: typeof DebugEncountersRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/characters/create": {
      id: "/characters/create"
      path: "/characters/create"
      fullPath: "/characters/create"
      preLoaderRoute: typeof CharactersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/saves/manage/$sessionId": {
      id: "/saves/manage/$sessionId"
      path: "/saves/manage/$sessionId"
      fullPath: "/saves/manage/$sessionId"
      preLoaderRoute: typeof SavesManageSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersCreateRoute: CharactersCreateRoute,
  DebugEncountersRoute: DebugEncountersRoute,
  DebugLlmRoute: DebugLlmRoute,
  DebugTerrainRoute: DebugTerrainRoute,
  GameHeroesRoute: GameHeroesRoute,
  GamePlayRoute: GamePlayRoute,
  GameSettingsRoute: GameSettingsRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  DebugIndexRoute: DebugIndexRoute,
  SavesIndexRoute: SavesIndexRoute,
  SavesManageSessionIdRoute: SavesManageSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
